version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/package"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"
    schedule:
      interval: "weekly"
